### PR TITLE
add templates for Debian 8.1.0 and 6.0.10

### PR DESCRIPTION
**Pull request by FunTimeCoding**
I used the 8.0.0 template and made it AMD64 only.

### CODE REVIEW

**Comment by FunTimeCoding** [comment]
Bump. =3 I asked about contributing in a tweet. I guess you're very busy.

**Comment by jedi4ever** [comment]
sorry I only have drip quality internet on holiday. hang on for another week:)

**Comment by FunTimeCoding** [comment]
Okay.

**Comment by KwadroNaut** [comment]
Nice @FunTimeCoding, I appreciate it that you continue having seperate i386 and amd64 templates.

**Comment by FunTimeCoding** [comment]
While I only use 64 bit vms and systems myself, I understand 32 bit still isn't fully gone and may even be more space and memory consuming on machines with less than 4gb of memory. I went with it since it seemed to be the common convention.

**Comment by favadi** [comment]
Any reason why it hasn't merged?

**Comment by ShiintoRyuu** [comment]
I think because the maintainer is awfully busy.

**Comment by mpapis** [comment]
thank you for reminding me about it!

**Pull request merged**
