### PR TITLE
Debian 8 (jessie) template

### PR DESCRIPTION
**Pull request by grahamrhay**
There've been a few changes to the preseed config, I think I've merged everything that's needed.

### CODE REVIEW

**Comment by mpapis** [comment]
can you merge them like it's done here: https://github.com/jedi4ever/veewee/tree/master/templates/CentOS-5.10 ?

**Comment by grahamrhay** [comment]
sure

**Comment by grahamrhay** [comment]
updated

**Comment by mpapis** [comment]
thank you!

**Pull request merged**
