### PR TITLE
New debian versions

### PR DESCRIPTION
**Pull request by FunTimeCoding**
New versions: 8.2, 7.9
Bug fix: missing net-scp dependency
Refactored: Debian 7 and 8 template version string

### CODE REVIEW

**Comment by FunTimeCoding** [comment]
Bump. I'm still alive, and I'm still offering to become a maintainer for this project.

**Comment by mpapis** [comment]
hey, what's up with failing tests?

**Comment by FunTimeCoding** [comment]
What should be up with them? net-scp is not backwards compatible?

**Comment by mpapis** [comment]
ok, tests fixed on master, please rebase

**Comment by FunTimeCoding** [comment]
You mean.. re-apply my changes on the current master?

**Comment by FunTimeCoding** [comment]
Oh, now net-scp is in there twice.

**Pull request merged**
