### PR TITLE
add Debian 9.1 template

### PR DESCRIPTION
**Pull request by FunTimeCoding**

### CODE REVIEW

**Comment by FunTimeCoding** [comment]
There has been issue #1106 @mpapis can you briefly look over this?

**Comment by rhtyd** [comment]
Thanks, I tried it seems to work for me.

**Comment by FunTimeCoding** [comment]
@mpapis seems rather busy, so I'm going to merge it myself.

**Comment by mpapis** [comment]
@FunTimeCoding indeed, but I'm working on getting more time for opensource... someday ;)

**Pull request merged**
