### PR TITLE
Copy Debian 7.9 to 7.10, adjust image locator and checksum

### PR DESCRIPTION
**Pull request by FunTimeCoding**

### CODE REVIEW

**Comment by mpapis** [comment]
hey, how about merging them into one? the amount of repeating code with copied templates reaches a new level ;) see https://github.com/jedi4ever/veewee/tree/master/templates/CentOS-5.10 for example of merging, if it's just location and checksum then it's worth merging them into one directory

**Comment by FunTimeCoding** [comment]
I thought about the same thing when I looked at my change set.

**Comment by FunTimeCoding** [comment]
There are more issues with Debian 6 templates. Most of them are somewhat broken since their mirrors changed to archive.debian.org. I'm still tinkering to try and get them to install (and post-provision) correctly by passing that mirror in the preseed.cfg.

**Comment by FunTimeCoding** [comment]
I also suspect that some download links may be broken. So I was wondering: Do we want to keep all the outdated versions? Can we create some form of usage statistic to determine how much legacy is needed?

**Comment by mpapis** [comment]
I do not think it will be easy to get the stats, for now we can merge the repeating templates code, ignore the errors, maybe we could have an automated scripts that would check existence of the images ... but that's separate chore

**Comment by FunTimeCoding** [comment]
Looking for feedback here. How should I name the template directory? Debian-7.x? Debian-7.x-amd64-netboot? Debian-7.9-7.10-amd64-netboot? Leave it as is?

Also: The older versions 7.8 and so on use a different format on the mirrors, called jigdo, which I believe veewee can't handle. http://cdimage.debian.org/cdimage/archive/7.8.0/amd64/jigdo-cd

Should we remove their templates or try to find a way to unpack them into isos?

**Comment by mpapis** [comment]
if we could merge it down to `Debian-7` - it would be great - if not the shortest possible is usually better

as for jigdo => https://github.com/jedi4ever/veewee/issues/951#issuecomment-57565910 - do they actually still use it? or is there so little interest for those cd's nobody noticed? what we can do is write a plugin for downloads that will depend on external program jigdo - and make it up to users to install it if they want that thing working

**Comment by FunTimeCoding** [comment]
Debian uses it even for archiving the current stable version http://cdimage.debian.org/cdimage/archive/8.1.0/amd64/jigdo-cd as you can see, and two releases back those are the only ones available, no more isos, to cut down on download costs. So Debian is relying on it and considers jigdo stable.

I think the interest in affected veewee templates has been so little that nobody wanted to fix it. I also have no use for any version other than the most recent ones of each major release.

**Comment by mpapis** [comment]
let's fix current version, we will reconsider jigdo support when someone else asks again

**Comment by FunTimeCoding** [comment]
@mpapis Did you see my most recent commit?

**Comment by mpapis** [comment]
no I did not, this looks amazing, exactly what I imagined for veewee :) please merge when ready

**Pull request merged**
